### PR TITLE
Major Update 2023

### PR DESCRIPTION
**Pull request by skyline-r34v**
## Title :
Updated the Website

## Description
1. Updated the website according to AY. 2023-2024

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Comment by demonkillerr** [comment]
I have reviewed it over the top, LGTM.

@vish-rt @tcet-opensource/web-team  you might want to have a look

**Comment by TejasNair9977** [comment]
hate to nitpick but could you fix the spelling of the magazine.html file @skyline-r34v

**Comment by 0amirk** [comment]
@skyline-r34v convert the jpgs to webp. They will be more efficient in terms of image size.

**Comment by skyline-r34v** [comment]
@TejasNair9977 --> Done with changing the file to magazine.html
@0amirk --> Converted all .png/jpg to webp

**Comment by 0amirk** [comment]
👍 GG @skyline-r34v

**Review by vish-rt — APPROVED** [review]

**Comment by vish-rt** [comment]
Your changes are deployed and is live on the subdomain

**Pull request merged**
